### ISSUE TITLE
Unable to point Pub to git repo

### ISSUE THREAD

**Issue by jimsimon** [dart-lang/reflectable#10]
I wanted to play around with the reflectable package a little bit but, due to the repo's folder structure, I'm unable to point my project at it.  Pub does not appear to support specifying a subpath within a git repo based dependency entry.  So the best I can do is point to the top-level directory which causes pub to complain that there's no pubspec.yaml file present.  Could you please consider either splitting the repo into two, or restructure the repo to be a valid dependency target for pub?

**Comment by eernstg** [comment]
We're publishing the `reflectable` package today, which should eliminate the `pub` issue. If similar problems arise elsewhere there is also a locally applicable workaround: Fetch the repository and use a `path` dependency on the local copy. With respect to the subpath into a git repo: I believe that it is a github policy to avoid supporting such a thing. With respect to splitting the repo into a separate `reflectable` repo and another separate `test_reflectable` repo: We want to keep these two packages together, such that we avoid version skew problems. I hope that this solves the problem!
