### ISSUE TITLE
Example links in readme are broken

### ISSUE THREAD

**Issue by matejthetree** [dart-lang/reflectable#116]
I get 404 github

**Comment by zoechi** [comment]
What link on what page?

**Comment by eernstg** [comment]
Thanks, they were all broken (because the directory structure of everything-reflectable has been reorganized completely). Will be fixed in the upcoming dev.3.0.

**Comment by zoechi** [comment]
Ups, missed that this is about reflectable. I thought it's in the sdk repo and thought this needs more info. Sorry for the noise.

**Comment by eernstg** [comment]
Anyway, it's always useful to include information about which links are broken. ;-)

**Comment by eernstg** [comment]
Fixed in [this PR](https://github.com/dart-lang/reflectable/pull/119/files).
