### ISSUE TITLE
How to see if class has mirrored superclass

### ISSUE THREAD

**Issue by matejthetree** [dart-lang/reflectable#122]
I would like to process class mirrors of superclass if they are reflected.

```
		ClassMirror classMirror = _refly.reflectType(type);

		void processClassMirrors(ClassMirror classMirror){
			_processableClassMirrors.add(classMirror);
			if (classMirror.superclass != null) {
				processClassMirrors(classMirror.superclass);
			}
		}

		processClassMirrors(classMirror);
```

But this

```
  ClassMirrorBase get superclass {
    if (_superclassIndex == NO_CAPABILITY_INDEX) {
      if (!_supportsTypeRelations(_reflector)) {
        throw new NoSuchCapabilityError(
            "Attempt to get `superclass` of `$qualifiedName` "
            "without `typeRelationsCapability`");
      }
      throw new NoSuchCapabilityError("Requesting mirror on un-marked class, "
          "`superclass` of `$qualifiedName`");
    }
    if (_superclassIndex == null) return null; // Superclass of [Object].
    return _data.typeMirrors[_superclassIndex];
  }
```

throws an NoSuchCapabilityError error. 

Is there a way to access `_superclassIndex` or to see somehow if I can access mirror on the superclass without using try/catch?

Thank you

**Comment by eernstg** [comment]
Would it hurt you to simply request mirrors for all superclasses? Check out `SuperclassQuantifyCapability` for how to do that. You could also check `myReflector.reflectedClasses`, but then (of course) you don't really have any way to investigate all the remaining superclasses when you've reached the first "hole".

**Comment by matejthetree** [comment]
Works great

**Comment by matejthetree** [comment]
One question, though
```
@Reflect()
class Clazz extends AbstractClazz with MixinClazz implements InterfaceClazz {
```

What classes will be reflected in this example if I use `SuperclassQuantifyCapability`? and what classes do I still need to `Reflect()` manually

Thank you
