### ISSUE TITLE
upgrade build_runner

### ISSUE THREAD

**Issue by thanizebra** [dart-lang/reflectable#140]
Resolving dependencies... (1.1s)
Because ui depends on reflectable 2.0.2 which depends on build_runner ^0.8.0, build_runner ^0.8.0 is
  required.
So, because toh depends on build_runner ^0.9.0, version solving failed.

**Comment by MikeMitterer** [comment]
Its related to https://github.com/dart-lang/reflectable/issues/136

**Comment by eernstg** [comment]
Closing: Done in [reflectable 2.0.3](https://pub.dartlang.org/packages/reflectable).
