### ISSUE TITLE
update dart 2

### ISSUE THREAD

**Issue by lyquocnam** [dart-lang/reflectable#141]
i tried install with dart 2 and error:
`Because reflectable >=2.0.2 depends on build_barback >=0.0.2 which requires SDK version >=1.9.1 <2.0.0 or >=2.0.0-dev.9 <2.0.0, reflectable >=2.0.2 is forbidden.
So, because darty depends on reflectable ^2.0.2, version solving failed.`
my dart version: `Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"`

**Comment by MikeMitterer** [comment]
Its related to https://github.com/dart-lang/reflectable/issues/136

**Comment by haarts** [comment]
(this is already fixed in https://github.com/dart-lang/reflectable/tree/eliminate_barback_jul18 I see)

**Comment by eernstg** [comment]
Closing: Release [2.0.3](https://pub.dartlang.org/packages/reflectable) works with the stable Dart 2 release.
