### ISSUE TITLE
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

### ISSUE THREAD

**Issue by Pareshoct7** [dart-lang/reflectable#144]
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because flutter_app depends on reflectable >=0.1.1 <2.0.2 which requires SDK version >=1.8.0 <2.0.0-dev.infinity, version solving failed.
pub get failed (1)

**Comment by eernstg** [comment]
I wrote the following in #141 when I closed it:

> Release 2.0.3 works with the stable Dart 2 release.

@Pareshoct7, as @zoechi mentioned the version conflict may disappear with a simple version upgrade operation. Otherwise please give some further information (say, about which `flutter_app` you are referring to).

**Comment by eernstg** [comment]
Closing: Given that reflectable 2.0.4 does not require an SDK version <2.0.0-dev.infinity, I'll assume that this issue is now obsolete. Please create a new issue in case the switch to the new version of reflectable does not resolve all the version conflicts.
