### ISSUE TITLE
Out of bounds error if `superclass` is not reflectable.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/reflectable#15]
https://github.com/dart-lang/reflectable/blob/fca4b3e597d7a2fbc9c5a61360b6d71fbf6eaf09/reflectable/lib/src/mirrors_unimpl.dart#L326 doesn't check if the index is -1, which it is in the case that the superclass is not reflectable. This should either throw with a more specific error message or return a stubbed out ClassMirror which throws whenever you try to call any methods.

Related to https://github.com/dart-lang/reflectable/issues/11.

**Comment by eernstg** [comment]
True; the missing check has been added (it now throws a `NoSuchCapabilityError` as it should). It will be part of the next commit.
