### ISSUE TITLE
Update dependency to build_runner 1.0.0

### ISSUE THREAD

**Issue by supermuka** [dart-lang/reflectable#154]
It is need to update dependency to build_runner 1.0.0.

With this definition on `pubspec.yaml`
```
dependencies:
  build_runner: ^1.0.0
  reflectable: ^2.0.7
```

_Update dependencies_ emits the following message:

> Because reflectable >=2.0.3 depends on build_runner ^0.10.0 and reflectable_test depends on build_runner ^1.0.0, reflectable >=2.0.3 is forbidden.
> So, because reflectable_test depends on reflectable ^2.0.7, version solving failed.

**Comment by eernstg** [comment]
Thanks for reporting! However, this is being addressed as #153, so I'll close this issue as a duplicate.
