### ISSUE TITLE
Version range for analyzer dependency too small for latest Flutter

### ISSUE THREAD

**Issue by suhlatwork** [dart-lang/reflectable#173]
Similarly to issue #163 (updating to previous stable Flutter), updating a project to the current Flutter stable 1.5.4 fails with unresolvable dependencies.

```
Because reflectable >=2.0.2 <2.0.10 depends on source_span >=1.0.0 <1.5.0 and reflectable >=0.1.1 <2.0.2 requires SDK version >=1.8.0 <2.0.0-dev.infinity, reflectable >=0.1.1 <2.0.10 requires source_span >=1.0.0 <1.5.0.
And because every version of reflected_mustache depends on reflectable ^2.0.0, every version of reflected_mustache requires source_span >=1.0.0 <1.5.0 or reflectable ^2.0.10.
And because reflectable >=2.0.9 depends on analyzer >=0.33.0 <0.35.0 and test_core >=0.2.2 depends on analyzer >=0.35.3 <0.37.0, if reflected_mustache any and test_core >=0.2.2 then source_span >=1.0.0 <1.5.0.
And because test >=1.6.1 <1.6.2 depends on test_core 0.2.3 and test >=1.6.2 depends on test_api 0.2.5, if reflected_mustache any and test >=1.6.1 then source_span >=1.0.0 <1.5.0 or test_api 0.2.5.
Because test >=1.3.0 <1.6.1 depends on stream_channel ^1.6.0 and test <1.3.0 requires SDK version >=1.8.0 <2.0.0-∞, test <1.6.1 requires stream_channel ^1.6.0.
Thus, if reflected_mustache any and test any then source_span >=1.0.0 <1.5.0 or test_api 0.2.5 or stream_channel ^1.6.0.
And because every version of flutter_test from sdk depends on both source_span 1.5.5 and stream_channel 2.0.0, if reflected_mustache any and test any and flutter_test any from sdk then test_api 0.2.5.
And because every version of flutter_test from sdk depends on test_api 0.2.4 and mde_flutter depends on reflected_mustache any, flutter_test from sdk is incompatible with test.
So, because XXX depends on both test any and flutter_test any from sdk, version solving failed.
```

The reason appears to be a discrepancy in the version range of the `analyzer` package (<0.35 by `reflectable`, >=0.35 by `test`/`test_api`).

Locally (and for the presumably small subset of functions from `reflectable` my dependencies use) I was able to work around this by simply allowing more recent versions of `analyzer` in `pubspec.yaml`. But in #163 you hint that this might not work in all cases. Does this still hold true?

```diff
 environment:
   sdk: '>=1.12.0 <3.0.0'
 dependencies:
-   analyzer: '>=0.33.0 <0.35.0'
+   analyzer: '>=0.33.0 <0.37.0'
   build: ^1.0.0
   build_resolvers: '>=0.2.0 <2.0.0'
   build_config: ^0.3.0
```

**Comment by eernstg** [comment]
This is indeed tricky because the analyzer interface has been restricted (reflectable uses features that do not exist any more). However, those features are unsupported by means of a `noSuchMethod` declaration, which means that they seem to exist (according to the static analysis of the reflectable code generator), but they throw at run time. I'm trying to find replacements for the missing features.

**Comment by eernstg** [comment]
Update: Problem not yet resolved, but the missing analyzer features (in particular `computeNode`) should be covered by other features (new names, signatures, but they should be able to do similar things). They involve asynchrony, however, so there may be a need to refactor a substantial amount of code.

**Comment by fertrig** [comment]
Hi @eernstg, do you have an update on this issue? I'm experiencing the same issue. I have some packages that depend on `analyzer ^0.36.0`, but reflectable depends on `analyzer >=0.33.0 <0.35.0`. Thanks!

**Comment by eernstg** [comment]
I've been working on it several times, but it's not trivial to reconstruct the behavior when a whole set of APIs that we've been using for years suddenly disappear. So no real news yet, unfortunately.

**Comment by e-belair** [comment]
@eernstg So what is your plan? Do you aim to maintain the project or abandon it?
Is there any alternative?
I tried to see the code in deep to see I could help, but it's too hard for me.

**Comment by eernstg** [comment]
I'd like to maintain it, but it's difficult to find the time. Given that 'dart:mirrors' is not supported on all platforms I don't think there is an alternative which is particularly similar.

Just FYI, here's an issue that creates a problem very early: https://github.com/dart-lang/build/issues/2310.

**Comment by eernstg** [comment]
Finally (with a 3000 line diff relative to 2.0.12), a branch of reflectable which uses analyzer 0.36.4 is starting to work: branch issue_173. ;-)

Among the many changes in the analyzer-as-used-by-package-build, it uses summaries rather than libraries from files to describe the platform libraries, which means that any attempt to get information about declarations in a platform library (i.e., one which is imported using a uri of the form `dart:*`) will stop as soon as it goes beyond a certain point. In particular, querying metadata or default values of parameters will just raise an exception. So some test cases are failing and are not likely to be revived right now.

**Comment by eernstg** [comment]
Closing: Just published v2.1.0 which is able to use analyzer 0.37.0 (and source_span 1.5.5, test 1.6.5, test_api 0.2.6). Note that the issue #180 (about missing information from platform libraries) still exists.

**Comment by e-belair** [comment]
@eernstg Thank you very much for your work. I'll update and test the new release asap and let you know about any issue. 
Thanks again!

**Comment by eernstg** [comment]
Sounds good!
