### ISSUE TITLE
Any plan for upgrading to latest build_runner

### ISSUE THREAD

**Issue by e-belair** [dart-lang/reflectable#176]
Is there a roadmap to upgrade compatibility according to the build_runner build_runner: ^1.3.0
and  build_web_compilers: ^2.0.0 ?

**Comment by eernstg** [comment]
The use of `build_runner ^1.3.0` implies `build_runner_core ^3.0.0`, and `build_runner_core >=2.0.2` implies `analyzer >=0.35.0 <0.37.0`.

That version of the analyzer eliminates a number of features that reflectable is using, so there's some repair work to be done before reflectable can be used with analyzer version 0.35.0 and up. This is being handled in #173, so I'll close this issue as a duplicate thereof.

PS: #173 has 'Flutter' in the title, but it is concerned with porting reflectable to analyzer 0.35, that requirement just came up in connection with Flutter first.

**Comment by e-belair** [comment]
Thank you for answering, I'll wait for any update about #173 issue.
