### ISSUE TITLE
initializeReflectable isn't defined in "void main"

### ISSUE THREAD

**Issue by klaszlo8207** [dart-lang/reflectable#177]

**Comment by eernstg** [comment]
Maybe you did not import the generated file? For `main.dart` to use reflectable, it should have

```dart
import 'main.reflectable.dart';
```

**Comment by klaszlo8207** [comment]
Main.dart:7:8: Error: Error when reading 'lib/main.reflectable.dart': 

How to generate that file?

**Comment by klaszlo8207** [comment]
I have this in build.yaml

targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - lib/Main.dart
        options:
          formatted: true

**Comment by klaszlo8207** [comment]
after this https://stackoverflow.com/questions/51169706/flutter-reflection-with-reflectable-working-example-needed

flutter packages pub run build_runner build lib/Main.dart

pub finished with exit code 64

**Comment by eernstg** [comment]
Here's a minimal example: https://github.com/eernstg/reflectable-flutter.

**Comment by klaszlo8207** [comment]
Thanks, now it is working...
