### ISSUE TITLE
Please help me in this, loop through static fields

### ISSUE THREAD

**Issue by klaszlo8207** [dart-lang/reflectable#178]
So

I have three classes

Strings.dart   //main Strings file
StringsEN.dart  
StringsFR.dart

I have the same static String names in it

example:

static String password= "password";

I d like to loop through the static fields key values, and IF I have the same static field name in the StringFR class then I want just update the main Strings static fields with that, is it possible?

What I tried first

 ClassMirror classMirror = reflector.reflectType(Strings);
    classMirror.staticMembers.forEach((k, v) =>  {

but here the v is something like MethodMirror and not the value of that field...thanks

**Comment by eernstg** [comment]
This one might be helpful: https://github.com/dart-lang/test_reflectable/blob/master/test/static_members_test.dart.

**Comment by klaszlo8207** [comment]
Tried it, but can not get the value of the field. Any idea how?

I want this:

static String password= "123456";

password -> 123456

Thanks!

**Comment by klaszlo8207** [comment]
ClassMirror classMirror = reflector.reflectType(Strings);

    classMirror.staticMembers.forEach((k, v) =>  {
      print ("------------- " + k.toString() + "   ---   " + classMirror.staticMembers[k.toString()].value )
    });


I want this:  classMirror.staticMembers[k.toString()].value

but value is not exists..

**Comment by klaszlo8207** [comment]
New error:)
Unhandled Exception: Attempt to get class mirror for un-marked class (type of 'listAnimals')

How to check if a static member is list?

**Comment by klaszlo8207** [comment]
Up

 NoSuchCapabilityError: no capability to invoke the getter 'newPassword'

I am trying to this

    ClassMirror classMirrorMAIN = reflectorMA.reflectType(Strings);
    ClassMirror classMirrorEN = reflectorEN.reflectType(StringsEN);

then

classMirrorMAIN.staticMembers.forEach((k, v) =>

then

        var mainValue = classMirrorMAIN.invokeGetter(k.toString());
        var enValue = classMirrorEN.invokeGetter(k.toString()); //here is the error

So what I want is to get the same static member name's values on that 2 classes, how to do that?

**Comment by eernstg** [comment]
There's an example of invoking a static getter [here](https://github.com/dart-lang/test_reflectable/blob/1fe727f5a67d4edc58f835aeba18d2968765653f/test/invoke_capabilities_test.dart#L180), and that's also what you would do in order to fetch the value of a static variable (variable `v` has a corresponding implicitly induced getter named `v` and, if not final, a setter named `v=`).

**Comment by klaszlo8207** [comment]
Thanks but why I get this to the second class mirror: NoSuchCapabilityError: no capability to invoke?

Can I use mirror more than one class at a time?

**Comment by klaszlo8207** [comment]
Sorry my bad, working like a charm!
