### ISSUE TITLE
Loosing files generation when webdev serve

### ISSUE THREAD

**Issue by e-belair** [dart-lang/reflectable#189]
Hi, I encounter an issue when I run webdev serve and the package reflectable.
Some files are not correctly generated, see this issue for more detail: https://github.com/dart-lang/reflectable/issues/186 

If I run `webdev build --output=web:build` the file main.reflectable.dart is randomly well generated
If I run `webdev serve web:53322 --auto refresh` the file is not completely generated and I get the capabilities errors.

webdev 2.5.4
build_vm_compilers: ^1.0.4
build_web_compilers: ^2.7.1
dart 2.6.1

**Comment by e-belair** [comment]
I think it's not a reflectable package issue, today I could generate the file properly ... It's surely a change detection problem as explained in the other ticket

**Comment by eernstg** [comment]
I can't see how 'main.reflectable.wrong.txt' could be created in the situation where 'main.reflectable.correct.txt' is the correct output. It looks like the set of classes delivered by the analyzer is too small (perhaps because it doesn't report all libraries). Is it likely that it matches up such that the missing elements correspond exactly to everything declared in some libraries and nothing declared in the remaining libraries?

**Comment by e-belair** [comment]
I've tried to import the entities affected by Reflector issue directly in main.dart and on build I get all the reflection for these classes. If I remove the import, I lost the reflection.
See my screencast here: https://youtu.be/wT0rszdyRLc
In my project, these classes are used like orm tables to auto load data used as list on html select, checkboxes ... and we have a lot of these tables. So I've created a service that auto fetch the data from the api:

```dart
  /// Return a list of given [Type]
  /// that can be used by the elementfactory
  ///
  /// eg with zonage model:
  /// [
  ///   {
  ///     "id_zonage": "a643fb703cfee948878c588d2b5882ea",
  ///     "lib_zonage": "Zonage économique"
  ///   },
  ///   [...]
  /// ]
  ///
  /// usage to get a List<Zonage>:
  /// zonages = getTableRefModel<Zonage>()
  Future<List<T>> getTableRefModel<T>(
      {WcfRequest request, bool cache = true}) async {
    request ??= WcfRequest();
    ClassMirror cm = reflector.reflectType(T);
    request.id = cm.invokeGetter('tableName');
    var datas = <T>[];
    var key;

    if (cache) {
      key = _cache.getHash(tableRefUrl + request.toJson().toString());
      var c = await _cache.get(key);
      if (c != null) {
        datas.addAll((json.decode(c) as List)
            .map((j) => cm.newInstance('fromJson', [j])));
        return datas;
      }
    }

    var response = await post(tableRefUrl, request: request);
    if (response.errors.isNotEmpty) {
      // todo raise error event
      return [];
    }
    var j;
    response.data['data'].forEach((data) {
      j = <String, dynamic>{};
      response.data['meta'].asMap().forEach((i, meta) {
        j[meta['name']] = data[i];
      });
      datas.add(cm.newInstance('fromJson', [j]));
    });
    if (cache) {
      await _cache.set(key, json.encode(datas));
    }

    return datas;
  }
```

**Comment by eernstg** [comment]
@e-belair wrote:
> I think it's not a reflectable package issue

I'll close this issue because I can't see any evidence that it would be a package reflectable issue, and the cited comment is aligned with this. Please re-open or create a new issue if some evidence to the contrary emerges.
