### ISSUE TITLE
Update bootstrap logic to have `test` package support.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/reflectable#19]
In order to write tests which are defined asynchronously, you need to return a future from main which doesn't complete until all tests have been set up. The current bootstrap logic for reflectable overwrites your main with a new one that has no return value [here](https://github.com/dart-lang/reflectable/blob/master/reflectable/lib/src/transformer_implementation.dart#L1440). The return type on `main` should be removed, and the original mains value should be returned, so roughly:
```dart
void main() {
  initializeReflectable();
  _main();
}
```
should become:
```dart
main() {
  initializeReflectable();
  return _main();
}
```

**Comment by eernstg** [comment]
Indeed, done (CL under review at https://codereview.chromium.org/1284013004/).
