### ISSUE TITLE
Will creating a generic instance of List be supported in the future?

### ISSUE THREAD

**Issue by HerrNiklasRaab** [dart-lang/reflectable#201]
Just a quick question: We are using the package "dart_json_mapper" but there seems to be no way to create a generic instance of a List: https://github.com/k-paxian/dart-json-mapper#iterable-types

Will this be supported in the future?
Does this depend on an issue not solved by for example the dart team?

Thanks,

Niklas

**Comment by eernstg** [comment]
There is no way in Dart to go from a reified representation of a type (which is an instance of type `Type` that was obtained by evaluating a type as an expression) to a language level type. In particular, you cannot create an instance of `List<T>` if the representation of `T` which is available is such a reified type.

```dart
bool b = true;

void main () {
  ... // May change `b`.
  Type type = b ? int : double;
  var xs = <type>[]; // Error; cannot obtain a language level type from `type`.
}
```

So in that sense this is a task that we cannot solve in Dart.

Of course, you can create and populate a `Map<Type, Function>` which will map a specific set of reified types to something, e.g., a factory function. But there is no general solution.
