### ISSUE TITLE
Stop using pkg:package_resolver

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/reflectable#205]
We're trying to discontinue it!

See https://github.com/dart-lang/package_resolver/issues/30

**Comment by eernstg** [comment]
Thanks for the notification! Commit https://github.com/dart-lang/reflectable/commit/64eee3241062b5eb9babf1cb372a9bdc6ca2a4d7 eliminates the dependency on `package_resolver`. However, `pub publish` currently crashes (cf. https://github.com/dart-lang/pub/issues/2410), so it cannot be published immediately.

**Comment by eernstg** [comment]
Reflectable 2.2.4 has now been published. Closing.

**Comment by kevmoo** [comment]
Thanks!
