### ISSUE TITLE
Incremental builds are getting slower and slower

### ISSUE THREAD

**Issue by HerrNiklasRaab** [dart-lang/reflectable#207]
A few weeks ago I noticed, that our reflectable builds were slowing down (incremental as well as non-incremental): https://github.com/dart-lang/reflectable/issues/188#issuecomment-600619300

I thought it would be related to this issue, but I am not sure if this is the same the same problem, that's why I am opening this one.

In the beginning, the **incremental** builds were just taking a few seconds (5 seconds) longer, but as the project progressed, those **incremental** builds were getting slower and slower (25s-30s). Now they it becomes quite unmanageable. You can just hit the run test button, you always need to wait for 30s to start the test again, which makes TDD impossible.

A few things that might help to resolve this:
- The project consists of 4 dart packages, each one has one entry point for tests. And one package is our actual flutter app, which has an additional entry point for the main.dart.
- The project size is moderate, nothing special
- The main.reflectable.dart (fazua_toolbox_app) for example (Flutter entry point) has 19222 lines and 536944 characters
- It is problem is os independent, means it occurs on Linux, macOS and Windows
- It feels like every incremental build throws away most of the cache and starts rebuilding more or less everything

If needed, I can provide the project to get it reproduced.

A long build time once wouldn't be a pain for use, just that that the incremental build is so slow is painful.

**Comment by HerrNiklasRaab** [comment]
@eernstg I know you have a lot to do, but maybe you know something we can do, with the blink of an eye. 

The following logs are of the 4 different packages we have. Every line has the project name as prefix. "fazua_toolbox_app" is a Flutter project.

Here are the logs of the reflectable builds:

> [INFO] Starting Build
> 
> fazua_domain: [INFO] ------------------------------------------------------------------------
> 
> [INFO] Starting Build
> 
> fazua_toolbox_app: [INFO] ------------------------------------------------------------------------
> 
> [INFO] Starting Build
> 
> fazua_dataaccess: [INFO] ------------------------------------------------------------------------
> 
> [INFO] Starting Build
> 
> fazua_application: [INFO] Updating asset graph...
> fazua_dataaccess: [INFO] Updating asset graph...
> fazua_domain: [INFO] Updating asset graph...
> fazua_toolbox_app: [INFO] Updating asset graph...
> fazua_application: [INFO] Updating asset graph completed, took 3ms
> 
> fazua_domain: [INFO] Updating asset graph completed, took 3ms
> 
> [INFO] Running build...
> fazua_application: [INFO] Running build...
> fazua_dataaccess: [INFO] Updating asset graph completed, took 3ms
> 
> fazua_dataaccess: [INFO] Running build...
> fazua_toolbox_app: [INFO] Updating asset graph completed, took 4ms
> 
> fazua_toolbox_app: [INFO] Running build...
> fazua_domain: [INFO] 1.0s elapsed, 0/1 actions completed.
> fazua_application: [INFO] 1.0s elapsed, 0/1 actions completed.
> fazua_dataaccess: [INFO] 1.0s elapsed, 0/1 actions completed.
> fazua_toolbox_app: [INFO] 1.1s elapsed, 5/21 actions completed.
> fazua_domain: [INFO] 2.1s elapsed, 0/1 actions completed.
> fazua_application: [INFO] 2.1s elapsed, 0/1 actions completed.
> fazua_dataaccess: [INFO] 2.1s elapsed, 0/1 actions completed.
> fazua_toolbox_app: [INFO] 2.3s elapsed, 25/39 actions completed.
> fazua_domain: [INFO] 3.1s elapsed, 0/1 actions completed.
> fazua_dataaccess: [INFO] 3.2s elapsed, 0/1 actions completed.
> fazua_application: [INFO] 3.2s elapsed, 0/1 actions completed.
> fazua_toolbox_app: [INFO] 3.3s elapsed, 45/58 actions completed.
> fazua_domain: [INFO] 4.2s elapsed, 0/1 actions completed.
> fazua_dataaccess: [INFO] 4.3s elapsed, 0/1 actions completed.
> fazua_application: [INFO] 4.3s elapsed, 0/1 actions completed.
> fazua_toolbox_app: [INFO] 4.4s elapsed, 73/87 actions completed.
> fazua_domain: [INFO] Running build completed, took 4.8s
> 
> [INFO] Caching finalized dependency graph...
> fazua_domain: [INFO] Caching finalized dependency graph completed, took 17ms
> 
> fazua_domain: [INFO] Succeeded after 4.9s with 1 outputs (1 actions)
> 
> fazua_toolbox_app: [WARNING] copy_with_extension_gen:copy_with_extension_gen on lib/bloc/bike_connection_bloc.dart:
> Missing "part 'bike_connection_bloc.g.dart';".
> fazua_dataaccess: [INFO] 5.3s elapsed, 0/1 actions completed.
> fazua_application: [INFO] 5.4s elapsed, 0/1 actions completed.
> fazua_dataaccess: [INFO] Running build completed, took 5.7s
> 
> [INFO] Caching finalized dependency graph...
> fazua_dataaccess: [INFO] Caching finalized dependency graph completed, took 18ms
> 
> fazua_dataaccess: [INFO] Succeeded after 5.7s with 1 outputs (1 actions)
> 
> fazua_toolbox_app: [INFO] 6.3s elapsed, 118/120 actions completed.
> fazua_application: [INFO] 6.4s elapsed, 0/1 actions completed.
> fazua_toolbox_app: [INFO] 7.4s elapsed, 118/120 actions completed.
> fazua_application: [INFO] 7.5s elapsed, 0/1 actions completed.
> fazua_application: [INFO] Running build completed, took 7.5s
> 
> [INFO] Caching finalized dependency graph...
> fazua_application: [INFO] Caching finalized dependency graph completed, took 15ms
> 
> fazua_application: [INFO] Succeeded after 7.5s with 1 outputs (1 actions)
> 
> fazua_toolbox_app: [INFO] 8.4s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 9.4s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 10.4s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 11.5s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 12.6s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 13.6s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 14.7s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 15.8s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 16.9s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 18.0s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 19.1s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 20.2s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [WARNING] No actions completed for 15.1s, waiting on:
>   - reflectable:reflectable on lib/main.dart
>   - reflectable:reflectable on test/main.dart
> 
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: StreamSubscription<T> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: S (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/future.dart:: Attempt to generate code for an unsupported kind of type: FutureOr<E> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: Stream<E> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:core/iterable.dart:: Attempt to generate code for an unsupported kind of type: Iterable<S> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: S (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: S (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: EventSink<T> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> /bloc/lib/src/bloc.dart:11:28: Attempt to generate code for an unsupported kind of type: State (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: Stream<State> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on lib/main.dart:
> /bloc/lib/src/bloc.dart:11:21: Attempt to generate code for an unsupported kind of type: Event (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: StreamSubscription<T> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: S (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/future.dart:: Attempt to generate code for an unsupported kind of type: FutureOr<E> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: Stream<E> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:core/iterable.dart:: Attempt to generate code for an unsupported kind of type: Iterable<S> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: S (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: S (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: T (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: EventSink<T> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> /bloc/lib/src/bloc.dart:11:28: Attempt to generate code for an unsupported kind of type: State (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> dart:async/stream.dart:: Attempt to generate code for an unsupported kind of type: Stream<State> (InterfaceTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [WARNING] reflectable:reflectable on test/main.dart:
> /bloc/lib/src/bloc.dart:11:21: Attempt to generate code for an unsupported kind of type: Event (TypeParameterTypeImpl). Generating `dynamic`.
> fazua_toolbox_app: [INFO] 22.0s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] 23.0s elapsed, 118/120 actions completed.
> fazua_toolbox_app: [INFO] Running build completed, took 23.9s
> 
> [INFO] Caching finalized dependency graph...
> fazua_toolbox_app: [INFO] Caching finalized dependency graph completed, took 57ms
> 
> fazua_toolbox_app: [INFO] Succeeded after 24.0s with 10 outputs (124 actions)

**Comment by HerrNiklasRaab** [comment]
This can be closed, we decided to remove all our code generation, from our project.

Why?
- Reflectable Limitations
- Bad Developer Experience
- Negative Return on Investment

The time I save with Hot Reload I spent on fixing problems from code generation.

**Comment by eernstg** [comment]
Hi @HerrNiklasRaab, it sounds like this issue is about the time taken to generate that 19222 line file. The incrementality of the process is exclusively about package build's ability to avoid running a code generator in the case where none of its inputs have changed. Reflectable itself is not incremental.

Another matter is that it might be useful to avoid running code generators automatically: The changes that trigger a re-run must err on the safe side (and package build doesn't know anything about _how_ any given code generator depends on its inputs). So if you're using reflection on a set of classes that don't actually change very often, you might be able to run code generation much less frequently.

I noted that you get a lot of `Attempt to generate code for an unsupported kind of type` warnings. That's a known limitation: When you request the ability to obtain the value of a type variable (using getters like `reflectedType`, `reflectedReturnType`, etc) code is generated to return the value `dynamic` instead, because there is no way you can generate regular Dart code that returns such a value. So if you actually don't need those reflected types (you just get them because you are requesting capabilities for a bunch of features, and it's too verbose to avoid getting them) then it should not be a problem.

In any case, I understand that you're going to do something else now. I hope your new approach will work out well!
