### ISSUE TITLE
Public fixnum field on PolymerElement causes reflectable to fail.

### ISSUE THREAD

**Issue by wienczny** [dart-lang/reflectable#25]
If you have a PolymerElement that contains a field with a type from the fixnum package like:
```
Int64 lastMessageId = Int64.ZERO;
```
the reflectable transformation fails with a message like
```
[Warning from Dart2JS]:
web/index.dart:34:3:
Cannot resolve getter.
  _initializeReflectable();
  ^^^^^^^^^^^^^^^^^^^^^^
```
If you "hide" the field from the outside like this:
```
Int64 _lastMessageId = Int64.ZERO;
```
it works. ;)

I could reproduce this by adding the above field to TodoList class of https://github.com/dart-lang/sample-todomvc-polymer/tree/polymer-0.17-behaviors and run pub build

Im using the latest reflectable, polymer and Dart VM version: 1.12.0 (Mon Aug 31 03:24:52 2015) on "linux_x64"

**Comment by sigurdm** [comment]
Problem was the handling of `operator ~`. https://codereview.chromium.org/1326283002 should mitigate this.

The reason that making the field private "solved" the problem is that we do not allow reflection on private fields.

**Comment by sigurdm** [comment]
Thanks for reporting!
