### ISSUE TITLE
git tag when publishing a new release to pub.dartlang.org

### ISSUE THREAD

**Issue by zoechi** [dart-lang/reflectable#26]
This would make it easy to see what changed between published versions and allow to check out specific version. 
```bash
git tag 0.1.5
git push --tags
```

**Comment by eernstg** [comment]
Done.

**Comment by zoechi** [comment]
:+1:

**Comment by eernstg** [comment]
Thx! ;)

On Tue, Sep 22, 2015 at 5:13 PM, Günter Zöchbauer <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/reflectable/issues/26#issuecomment-142319839>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984
