### ISSUE TITLE
InstanceInvokeMetaCapability doesn't match meta which extends/implements specified classes

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/reflectable#29]
The [implementation](https://github.com/dart-lang/reflectable/blob/3d8785c99e221776c3d4c74f8448e18d0e6072b0/reflectable/lib/src/reflectable_mirror_based.dart#L121) of `metadataSupported` doesn't match metadata which extends or implements the supported metadata, it only matches if the runtimeType exactly matches the type of the metadata:

```dart
/// Returns true iff an element of the [metadata] is supported by the
/// [capability].
bool metadataSupported(
    List<dm.InstanceMirror> metadata, MetadataQuantifiedCapability capability) {
  return metadata
      .map((dm.InstanceMirror x) => x.reflectee.runtimeType)
      .contains(capability.metadataType);
}
```

**Comment by eernstg** [comment]
Fixed in CL https://codereview.chromium.org/1350053003/.

**Comment by eernstg** [comment]
Landed.
