### ISSUE TITLE
Capability:  Access metadata

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/reflectable#3]
For dart2js there will be the desire to control which metadata is retained.  The most useful way to filter is probably by the `Type` of the metadata items.

I am particularly hoping that doc-comments can be encoded as metadata as well, see:

http://dartbug.com/15704

So I could specify I want to retain `Comment`s for example.

**Comment by eernstg** [comment]
Please see #6 on dartbug 15704 for some additional information.  Reflectable mirrors are intended to be very similar to mirrors from dart:mirrors, so they should agree on the treatment of doc comments.  

However, this feature can be implemented independently in dart:mirrors and in Reflectable for post-transform code (whereas pre-transform code in Reflectable relies on dart:mirrors), so I added a reminder in the code to include comments in `metadata` of `DeclarationMirror`.

Currently `dart:mirrors` mirrors do not include doc (or other) comment mirrors in the `metadata`, but when they do that, there may be a need to adjust the semantics for precise alignment among dart:mirrors and Reflectable.  (As an extreme example of this, the outcome may even be that it is decided that `dart:mirrors` should *not* support comments as `metadata`, for backward compatibility or whatever, in which case Reflectable may have to align with the lack of support).  In any case, there will be a "temporary feature, do not rely on this in production code" flag on this feature for now.

Also note that the implementation of Reflectable is still highly incomplete, so it will not yet be possible to try it out at this point.
