### ISSUE TITLE
Given a getter/setter pair, InstanceInvokeMetadataCapability should only require an annotation on one.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/reflectable#42]
Maybe this should be an entirely new capability, but I think its a pretty fair assumption that you would want access to both the getter and the setter by the same name, and annotating both is cumbersome. See https://github.com/dart-lang/polymer-dart/issues/621.

**Comment by eernstg** [comment]
That's true, we don't have any closures for members, only for classes. Interesting! ;)

Added a new `correspondingSetterQuantifyCapability` which will extend every mirror system where an explicitly declared getter is already included with the corresponding explicitly declared setter, if any.

It's in https://codereview.chromium.org/1387383006/, I hope to be able to publish a new release today that includes it.

**Comment by eernstg** [comment]
Done in commit 7800cb0a48b7cdf3561337de3374398b2980b9ba. A new version will be published in a few days, but we had some more bugfixes for that, too.
