### ISSUE TITLE
Multi field declaration fails

### ISSUE THREAD

**Issue by zoechi** [dart-lang/reflectable#44]
should this work?

```dart
class Name extends JsProxy {
  @reflectable String first, last;
  // also not possible
  // @reflectable String first, @reflectable last;
  Name(this.first, this.last);
}
```
I didn't get an error message, just launching the Polymer app failed.

I don't especially need or want this, just encountered it while working on some Polymer examples.

**Comment by eernstg** [comment]
Thanks for the report, that should definitely be supported! Marked as a bug.

**Comment by eernstg** [comment]
The CL at https://codereview.chromium.org/1421713004/ was created with the new 'multi_field_test.dart' as a starting point, which should address any issues you may have seen with the above code snippet.

**Comment by eernstg** [comment]
Above-mentioned CL has now been committed as 2b00afb7c57be7d6dca03f4cff7d7bbd21beb172 on https://github.com/dart-lang/reflectable. Interestingly, I did not encounter any issues with multiple declarations with the same type annotation (even though that was a case that we didn't test), but several issues with top level declarations were fixed. Please create a new ticket if any issues remain.
