### ISSUE TITLE
Allow access to both getter and setter of a property when either is annotated according to InstanceInvokeMetaCapability 

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/reflectable#52]
It would be very nice if you could use InstanceInvokeMetaCapability to reflect on properties without requiring that both getter and setter be annotated with the specified type, either as the default behavior of through additional config. It's less ideal that users of my library have to annotate both getter and setter of every property that they want to have processed when the thing it does always involves both reading and modifying the property value. Currently I have to resort to InstanceInvokeCapability without a name pattern. 

On a more general note, as a user of Reflectable it would just feel more natural if properties were given at least partially first-class treatment instead of them just being linked by name.

**Comment by sigurdm** [comment]
Hi Lasse. Thanks for the suggestion. I believe you are looking for already exists:
```
/// Quantifying capability instance specifying that the reflection support
/// for any given explicitly declared getter must also be given to its
/// corresponding explicitly declared setter, if any.
const correspondingSetterQuantifyCapability = [...]
```

About the general note - can you give an example of how the code you imagine would look like? I'm not sure I follow exactly what you mean by "first-class treatment". Preferably in a new issue.
