### ISSUE TITLE
Update to use analyzer `^0.27.0`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/reflectable#54]
Last I heard there were some issues, but we need to get those resolved and update. This is the final dependency of `polymer` which needs to be updated.

**Comment by eernstg** [comment]
I'm waiting for analyzer 0.27.1 which will resolve the "libraries whose constants are null" issue. Brian just got my response on this, I think he will have an update ready soon.

**Comment by jakemac53** [comment]
ok great, if you wouldn't mind leaving this open just so I can track the progress that would be awesome

**Comment by eernstg** [comment]
Sure!

**Comment by eernstg** [comment]
Trying out the version of analyzer that Brian mentioned (1f3dabd9c7ef391c468d2697294695194a67c569): That does not fix the problem, we still get null from evaluation of constants, where we get non-null with 0.26.1+14.

**Comment by eernstg** [comment]
Cf. https://codereview.chromium.org/1486663003/

**Comment by eernstg** [comment]
Commit 406b87e1952d51abc6c79ef6b3f4c1e70f0d4e87 has been published as version 0.5.0, which uses analyzer ^0.27.0 and code_transformers ^0.3.0. Note that this version contains several breaking changes. In particular, several methods including `instanceMembers` will now require `declarationsCapability`, as specified in the design document, but previously not enforced; no-such-method situations will throw a `ReflectableNoSuchMethodError`; the methods `bestEffort..` have been deprecated (they are conceptually ill-defined; please replace call-sites for them by their method bodies, which are trivial); finally, please check CHANGELOG.md for more details.

**Comment by eernstg** [comment]
One step backwards: Package-bots are now failing for reflectable, and a local test shows that it fails with the most recent analyzer (0.27.1+1) and works with an added constraint to stay with 0.27.1. Will land a commit that includes this constraint. We may have to publish it, too.

**Comment by eernstg** [comment]
We just landed commit efbfd3b0f05953fc02074061e3204090283029d4 and published it as version 0.5.1, which depends on analyzer 0.27.1 (just that single version). This is a temporary measure, because it is very inconvenient for the larger context to have narrow constraints like that, but analyzer 0.27.1 is currently the only version in ^0.27.0 that will work.

**Comment by eernstg** [comment]
Re-opening this issue until the `evaluationResult` issue has been resolved.

**Comment by eernstg** [comment]
Awaiting an analyzer that fully resolves constants, or one that allows us to request resolution when we encounter an unresolved constant.

**Comment by eernstg** [comment]
Turns out that there is a need to adjust `code_transformers` and/or the analyzer: The features needed in order to request resolution are available in the analyzer, but reflectable does not have access to make those calls. More details in https://github.com/dart-lang/sdk/issues/24890.

**Comment by eernstg** [comment]
Wow, I've got something that works now! \o//
Testing, double-checking, etc.

**Comment by eernstg** [comment]
https://codereview.chromium.org/1761423002/ uses the lazy and fine-grained constant resolution based on `Resolver.computeLibraryElement` that we discovered recently. That should resolve this issue.

**Comment by eernstg** [comment]
Addressed by https://github.com/dart-lang/reflectable/commit/543ad76b62681b9cb2a49c163cbefa34d4b521bd. Note that this commit actually uses ^0.27.2 rather than ^0.27.0.
