### ISSUE TITLE
Make names of generated classes unique.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/reflectable#6]
Currently if we have

    @MyReflectable
    @MyReflectable2
    class A{}

We will generate two classes called `Static_A_InstanceMirror` and 2 called `Static_A_ClassMirror`.
Also two classes with the same name in different libraries give rise to a clash.
They should have globally unique names.
Perhaps something like `MyReflectable2_liba_A_InstanceMirror`.

**Comment by eernstg** [comment]
This issue was implicitly resolved when we stopped generating mirror classes (we now only generate code for instances of the existing class `ClassMirrorImpl`).
