### ISSUE TITLE
Declarations of a native (dart.*) libraries are empty

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/reflectable#62]
The following code returns an empty Map:
```dart
reflector.findLibrary("dart.io").declarations
```
The reflector has following capabilities: `libraryCapability, declarationsCapability`.

**Comment by eernstg** [comment]
Did you include any declared entities in that library?

Class `C` can be included by adding an annotation to it (`@reflector class C ..`), but with native libraries (or anything which is outside the current package) you need to use a global quantifier to get it included. Check out examples like https://github.com/dart-lang/reflectable/blob/master/test_reflectable/test/global_quantify_test.dart and https://github.com/dart-lang/reflectable/blob/master/test_reflectable/test/meta_reflectors_test.dart to see how `@GlobalQuantifyCapability` can be used to get support for classes outside your current package.

**Comment by stevenroose** [comment]
That solves the problem, indeed!
