### ISSUE TITLE
How to access static fields (getters)?

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/reflectable#66]
The capability `StaticInvokeCapability` is documented
> Gives support for reflective invocation of static members (static methods, getters, and setters) 

I tried to invoke the getter with this methods:
`classMirror.invoke(field, []);`, 
`classMirror.invokeGetter(field);`,
but I always get this error"
```
Unhandled exception:
NoSuchCapabilityError: no capability to invoke the method 'FACTORY_CONFIG'
Receiver: null
Arguments: []
```
The `classMirror` object is certainly not null, I checked that, so the "receiver" mentioned is something internal. 

For completeness, these are capabilities I have: `libraryCapability, staticInvokeCapability, declarationsCapability, newInstanceCapability, typeRelationsCapability`

**Comment by stevenroose** [comment]
I tried adding all available capabilities and the error persists. So I suspect this to be either a bug or I'm trying to call them in an incorrect way.

**Comment by jakemac53** [comment]
Were you able to resolve this issue? Polymer is using this so it's definitely possible.

**Comment by stevenroose** [comment]
Yeah, it was my bad. I had one case where the receiver was indeed null, but
with every test all cases were loaded, so I thought all cases were giving
the error. It's fixed now.
