### ISSUE TITLE
Issue with static Reflectors

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/reflectable#68]
I had a problem with a class not being included in my `Reflectable` instance, and I think I nailed it down to this issue:

Consider you have a library of two files:
```dart
library test;
part "test_part.dart";

class SomeClass {
  static const Reflectable reflector = const MyReflectable();
}

class MyReflectable extends Reflectable {
  const MyReflectable() : super(someCapabilities);
}
```
```dart
part of test;

@SomeClass.reflector
// analyzer: ERROR: Annotation can be only constant variable or constant 
// constructor invocation
class ShouldBeReflected {
}
```

In that case, at least for me, the `ShouldBeReflected` class is not available for `MyReflectable` (library `test` is not in the `reflector.libraries` set). When I change the second file to this, it does work:
```dart
part of test;

@MyReflectable()
class ShouldBeReflected {
}
```

EDIT: For a `GlobalQuantifyCapability`, it does seem to work. So `@GlobalQuantifyCapability(regex, SomeClass.reflector)` works for me.

EDIT2: I forgot to mention that I only have this problem with transformed code, not in the VM.

**Comment by eernstg** [comment]
`SomeClass.reflector` is not a const, so the program should be rejected when such an expression is used as an annotation. It is known that the vm is more flexible than it should be for this type of situation, but `dartanalyzer` should complain. We have in general made the assumption that entry points to transform have been checked for language level correctness. What happens if you change `SomeClass.reflector` to be a const?

**Comment by stevenroose** [comment]
Ah, I'm sorry. It is const in my project. I made a mistake in my dummy example here. I'll correct it. 

But I notice now that, even though const, the analyzer now errors. (I migrated my setup to a different OS, so it might be different versions of SDK/IDEA plugin.)

So, I updated the example above and added the analyzer error. Now it actually becomes even more strange.

I tried restarting the analyzer process.

**Comment by eernstg** [comment]
I don't know why the analyzer complains about `@SomeClass.reflector` now.

But I suspect that the form `@ClassName.memberName` is not recognized by the transformer (we have to check for each supported syntactic form separately and "interpret" it at compile time). So could you try to use a simpler syntactic form as a work-around for now? E.g., define a top level const `SomeClassReflector` meaning the same thing, such that the metadata expression will be a plain identifier.

Then we'll look into the handling of the form using `.` as soon as possible.

**Comment by stevenroose** [comment]
Yes, I do now just use the `@Reflector()` syntax. In fact it's good that the analyzer complains because it does not work. So that's less confusing. (Even though the error it gives about it not being constant is wrong, it's still better than no error and just not working.)

So for now it is ok, just require the constant constructor to be used instead of static variables.

**Comment by eernstg** [comment]
CL https://codereview.chromium.org/1691003002/ adds support for recognizing reflector metadata on the form `@SomeClass.reflector` where `SomeClass` is a class and `reflector` is a static const field.

**Comment by stevenroose** [comment]
Super, I think I can close this then..
