### ISSUE TITLE
Support annotation on imports or library deffinition

### ISSUE THREAD

**Issue by re222dv** [dart-lang/reflectable#7]
It would be great if it was possible to add an annotation to an import or library definition to make it possible to serialize all classes in that library.

I tend to stuff all my entity classes into a single library and it's unnecessary tedious to place an annotation over all classes in that library.

**Comment by eernstg** [comment]
We're currently discussing the design of the `ReflectCapability` hierarchy and its semantics (you could consider the specification of capabilities as a domain specific language, and we are discussing the design of that language). This certainly includes the ability to specify requests for reflection support away from the target itself. For instance, a program could request support for reflection on instances of a class in dart:core or somewhere else "out of reach". This concept has been known as 'SideTags' for a while. It might look like this:

```dart
  @ReflectImported(const [Foo, Bar], myReflectable)
  import 'package:foo_bar/foo_bar.dart';
```
which would have the same effect as having `@myReflectable` on `class Foo {..}` and `class Bar {..}` in `foo_bar.dart`. We also plan for quantification, e.g., the ability to say things like

```dart
  @ReflectSubtypes(myReflectable)
  class Foo {
    ...
  }
```
which will have the same effect as putting `@myReflectable` on all subtypes of `Foo`. We expect liberal quantification to make sense for less critical applications (more space will be wasted if many classes support reflection, but it is never actually used), and more tightly specified quantification (or no quantification, just concrete choice of classes one by one) would be justified in cases where the space consumption must be under very tight control.

**Comment by Pajn** [comment]
That sounds great, the ability to choose is great as it can fit all use cases.
My request then is that `ReflectImported` can be used without specifying types at all to get all of them, like `@ReflectImported(myReflectable)`.

**Comment by eernstg** [comment]
That should be easy, too. Noted.
