### ISSUE TITLE
Document the required capabilities for each method in the API

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/reflectable#70]
This is more a long-term goal than an issue right now. Most of the time, it is rather clear what capabilities are required for each method in the API, but not always.

In the end, I think it should be possible for a user to look at the API documentation to see what functionality he wants to use and know from the documentation all the capabilities he requires.

**Comment by floitschG** [comment]
Great feature-request!

**Comment by eernstg** [comment]
+1! that's definitely a useful thing to do, that we have sort-of had in mind for a long time.

**Comment by eernstg** [comment]
Finally, the 'Required capabilities' information on dartdoc comments has been filled in for all the mirror methods (and some method implementations have been adjusted for consistency with the documentation and for better diagnostic messages):  1746dc6e06297bbdfeff378d2901e767224bd079.
