### ISSUE TITLE
subtypeQuantifyCapability skips a lot of classes

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/reflectable#71]
It's hard to produce reproduction here. But this is what I stumbled upon this:

First, I had a `@GlobalQuantifyCapability` over all `mypackage.impl.*` libraries. (These libraries are imported, but no classes from them are called directly, so I get a lot of "Unused import" warnings.)

Now I realized that I only needed the classes that are a subtype of one class I have also reflected on with an annotation. So I removed the `@GlobalQuantifyCapability` and added the `subtypeQuantifyCapability` to my reflector. Thus, I only have a single annotated class: a superclass that a lot of imported classes implement (indirectly).

Now, interestingly, when iterating over `reflector.annotatedClasses` (which is already a wrong name because it should actually only contain the one class instead of all other classes reflected on) contains some of the subclasses of the superclass, but far from all of them. There is a pattern: the main library that makes all the imports, also specifies some exports. So, all classes exported by this library are present and the ones only imported and then not being uses, are not. Whether or not this is intended behavior, is nowhere documented, but I do know that this was not the case when using the `@GlobalQuantifyCapability`.

**Comment by sigurdm** [comment]
Is this still an issue?

**Comment by stevenroose** [comment]
No. I made a mistake. That's why I closed it immediately.

**Comment by sigurdm** [comment]
No problem
