### ISSUE TITLE
Including instanceInvekeCapability throws a misleading exception

### ISSUE THREAD

**Issue by TastyCatFood** [dart-lang/reflectable#73]
<strong>This one was my mistake for not updating pubspec, sorry guys and laugh at a fool here</strong>

What is wrong:

1. Invalid argument exception does not provide a clue about the location of an offending code but where an InstanceMirror is used.

2. Available capabilities and required capabilities for using Mirror features are unclear

> I wanted to get a list of functions on an object and failed due to one of the three, my idiocy, not including necessary capability, a bug. Daunting. 

Supplementary info
What triggered the exception:
Using "instanceInvokeCapability", commenting the line suppressed the error.

The capabilities used 
<code><pre>
class Reflector extends Reflectable{
  const Reflector():
        super(
          instanceInvokeCapability,
          declarationsCapability,
          nameCapability,
          typeCapability,
          metadataCapability,
          classifyCapability
      );
}
</pre></code>

Exception thrown:
<code><pre>
 Uncaught Unhandled exception:
Invalid argument(s)
#0      List.[] (dart:core-patch/growable_array.dart:135)
#1      ImplicitAccessorMirrorImpl._variableMirror (package:reflectable/src/reflectable_transformer_based.dart:1162:26)
#2      ImplicitGetterMirrorImpl.simpleName (package:reflectable/src/reflectable_transformer_based.dart:1248:28)
#3      ClassMirrorImpl.instanceMembers (package:reflectable/src/reflectable_transformer_based.dart:347:34)
#4      RunnablePuzzle.RunnablePuzzle (package:quiz/quiz/gui_runnable_puzzle.dart:46:35)
#5      main.<main_async_body> (http://localhost:63342/quiz/web/index_reflectable_original_main.dart:20:32)
#6      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _ScheduleImmediateHelper._handleMutation (dart:html:49254)
#10     MutationObserver._create.<anonymous closure> (dart:html:27525)
</code></pre>

At line 46 of gui_runnable_puzzle.dart I have:
 "    var methods = selfMirror.type.instanceMembers;"
"text-piece" is a non-polymer custom html element.
<code><pre>
    var selfMirror = reflector.reflect(querySelector('text-piece'));
    selfMirror = (selfMirror as InstanceMirror);
    var methods = selfMirror.type.instanceMembers;
    print(methods.runtimeType);
    print(methods.length);
    for(var k in methods.keys) print('key:'+k.toString());
</code></pre>

**Comment by sigurdm** [comment]
This looks like a bug. Can you provide a working example (preferably including a pubspec and html)?

**Comment by sigurdm** [comment]
Is this issue resolved? Can you briefly describe what was the problem and solution, in case others find this post, and are in a similar situation?

**Comment by TastyCatFood** [comment]
I was using Intellij generated pubspec.yml which contained an older version of reflectable as below.
dependencies:
  browser: ^0.10.0
  reflectable: ^0.3.1
  web_components: ^0.12.0

With the above configuration, pub get installs:
|-- reflectable 0.3.4
|   |-- analyzer...
|   |-- barback...
|   |-- code_transformers...
|   |-- dart_style 0.2.1
|   |   |-- analyzer...
|   |   |-- args...
|   |   |-- path...
|   |   '-- source_span...
|   '-- logging 0.11.2


In reflectable 0.3.4, attempting to use instanceInvokeCapability throws the aforementioned exception.

I was updating dart-sdk but was neglecting to update pubspec...somehow.
I wasted a day..wow.

**Comment by sigurdm** [comment]
What a shame. Managing dependencies can be frustrating at times.
Happy you made it work in the end.

**Comment by zoechi** [comment]
> I was using Intellij generated pubspec.yml 

means https://pub.dartlang.org/packages/stagehand I guess.
Is there something outdated?

I always run `pub upgrade` in the console. This nicely shows where new versions are available.
