### ISSUE TITLE
InstanceMirror.type.instanceMembers returns an empty  UnmodifiableMapView<String, MethodMirror>

### ISSUE THREAD

**Issue by TastyCatFood** [dart-lang/reflectable#74]
What is wrong:

1. InstanceMirror.type.instanceMembers returns an empty  UnmodifiableMapView<String, MethodMirror>

Why is it wrong:
Provides no clue for resolution and the cause.
 
> When 'dart:mirrors' is used, the return value is not empty.  I'm clueless if it is a missing capability or my blunder or a bug.

The capabilities used 
<code><pre>
class Reflector extends Reflectable{
  const Reflector():
        super(
          declarationsCapability,
          nameCapability,
          typeCapability,
          metadataCapability,
          classifyCapability
      );
}
</pre></code>

Dartium console output:
<code><pre>
UnmodifiableMapView<String, MethodMirror>
0
</code></pre>

Code:
"text-piece" is a non-polymer custom html element, the code has been tested with 'dart:mirrors'.
<code><pre>
    var selfMirror = reflector.reflect(querySelector('text-piece'));
    selfMirror = (selfMirror as InstanceMirror);
    var methods = selfMirror.type.instanceMembers;
    print(methods.runtimeType);
    print(methods.length);
    for(var k in methods.keys) print('key:'+k.toString());
</code></pre>

**Comment by sigurdm** [comment]
Thanks for the report.
Can you give a full reproducing example?
Are you seeing this when running transformed or untransformed (or both)?

**Comment by TastyCatFood** [comment]
Transformed, I will upload the example shortly

**Comment by sigurdm** [comment]
Thinking more about it, I think you need `instanceInvokeCapability`. Quoting the documentation for `declarationsCapability`:

> Gives support for: declarations, instanceMembers, staticMembers, callMethod, parameters, and defaultValue.

> Note that it is useless to request this capability if no other capabilities have given rise to the generation of source code related mirror classes, because these methods are only defined by those mirror classes.

Note the second paragraph. `declarationsCapability` only gives access to the declarations of the members that are selected with the different "invoke"-Capabilities

**Comment by TastyCatFood** [comment]
Hi, sigurdm
Here my complaint is list being empty rather than NoSuchCapability.
After Including "instanceInvokeCapability", it works. 

As to my other post, sorry. 
I will check pubspec every morning from this day on.

https://github.com/TastyCatFood/dart-reflectable-empty-UnmodifiableMapView-issue-reproduced

**Comment by sigurdm** [comment]
The documentation might not be stating it clearly enough, but as soon as you have declarationsCapability, you are allowed to call `.instanceMembers`, but what it returns depends on what members are selected by other capabilities.
So this is actually working as intended.

**Comment by TastyCatFood** [comment]
Thank you sigurdm and sorry about all the troubles.
Hope post keeps someone from making the same mistake.   

have a lovely day.

**Comment by sigurdm** [comment]
No problem - happy you got it to work.
