### ISSUE TITLE
Cannot re-create default values.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/reflectable#8]
With the interface the analyzer currently present us it is very difficult to reproduce a constant from the default value to a function parameter in generated code. 

For a simplified example, given:

    class A {
      A([a = XXXX]);
    }
We would like to be able to produce:

    newInstance(List arguments) {
      Function x = ([a = YYYY]) => new A(a);
      Function.apply(x, arguments);
    }

Such that `YYYY` has the same value as `XXXX`.
For example if we have:

    class A {
      static const c = 10;
      A([a = c]);
    }

then letting `YYYY = XXXX` will fail.
This might be possible after a resolution of: https://github.com/dart-lang/sdk/issues/17307.
When we have generalized tearoffs: dart-lang/dart_enhancement_proposals#3 this issue might disappear.

**Comment by sigurdm** [comment]
When we have generalized tearoffs: https://github.com/dart-lang/dart_enhancement_proposals/issues/3 this issue might disappear.

**Comment by sigurdm** [comment]
To clarify: just using XXXX does not give the same value in a different scope.

**Comment by eernstg** [comment]
Just considering a possible work-around: Is there an easy way to tell how many levels of _lifting_ any particular piece of code will tolerate without getting a different semantics? (by 'lifting' I mean: moving a piece of code from inside to outside a given scope, similar to lambda lifting and similar to loop invariant expression hoisting). For code in a constructor or method argument list default expression, we'd just need to know that we can lift the expression one level (to global), and then we'd control the target context well enough (we're generating it) to make sure the expression doesn't get a different semantics when inserted there. This means that we would be able to use the naive approach for moving the code as long as it works, and then we could bail out with an error message in the cases where something more elaborate is needed (or we could run some other algorithms and cover more and more cases as we proceed, leaving fewer and fewer cases unimplemented).

**Comment by eernstg** [comment]
Closing this issue: Implemented support for a number of special cases (including default value expressions which have no local dependencies such as literals, and expressions which are simple identifiers looked up in the same class or top-level of the same library); missing cases (e.g., using `const somePrefix.C()` as a default value or using `@somePrefix.C()` as metadata) will give rise to an error during transformation. We'll need extra tests for the missing cases as well, but this will enable a lot of simple usages of default values and annotations to work, and the remaining cases can be considered as bugs that we will fix along the way.

**Comment by sigurdm** [comment]
Reopening, as we do not support all constants yet.

**Comment by sigurdm** [comment]
I am convinced now that except for private constants (and that's a different issue) we can reconstruct all constants.
